apiVersion: apps/v1
kind: Deployment
metadata:
  name: row-selector-superset
  namespace: default
  labels:
    app: row-selector
    database: superset
    table: ab_permission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: row-selector
      database: superset
      table: ab_permission
  template:
    metadata:
      labels:
        app: row-selector
        database: superset
        table: ab_permission
    spec:
      containers:
      - name: row-selector
        image: frenoid/row-selector:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_HOST
            value: "tidb-norman-tidb.tidb-norman.svc.cluster.local"
          - name: MYSQL_USER
            value: "superset"
          - name: MYSQL_PASSWORD
            value: "superset"
          - name: MYSQL_PORT
            value: "4000"
          - name: MYSQL_DATABASE
            value: "superset"
          - name: MYSQL_TABLE 
            value: "ab_permission"
          - name: QUERY_INTERVAL
            value: "1"
